from flask import Flask, jsonify, request
from flask_cors import CORS
import subprocess
import json

app = Flask(__name__)
CORS(app)

@app.route('/api/devices', methods=['GET'])
def get_devices():
    """Scanner et lister les appareils Bluetooth à proximité"""
        try:
                # Exécute la commande de scan Bluetooth
                        result = subprocess.run(
                                    ['bluetoothctl', '--timeout=10', 'scan', 'on'],
                                                capture_output=True,
                                                            text=True,
                                                                        timeout=15
                                                                                )
                                                                                        
                                                                                                # Récupérer la liste des appareils
                                                                                                        devices_result = subprocess.run(
                                                                                                                    ['bluetoothctl', 'devices'],
                                                                                                                                capture_output=True,
                                                                                                                                            text=True
                                                                                                                                                    )
                                                                                                                                                            
                                                                                                                                                                    devices = []
                                                                                                                                                                            for line in devices_result.stdout.split('\n'):
                                                                                                                                                                                        if line:
                                                                                                                                                                                                        parts = line.split(' ', 2)
                                                                                                                                                                                                                        if len(parts) >= 3:
                                                                                                                                                                                                                                            devices.append({
                                                                                                                                                                                                                                                                    'address': parts[1],
                                                                                                                                                                                                                                                                                            'name': parts[2]
                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                return jsonify({'success': True, 'devices': devices})
                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                            return jsonify({'success': False, 'error': str(e)}), 500

                                                                                                                                                                                                                                                                                                                                            @app.route('/api/connect', methods=['POST'])
                                                                                                                                                                                                                                                                                                                                            def connect_device():
                                                                                                                                                                                                                                                                                                                                                """Connecter à un appareil Bluetooth"""
                                                                                                                                                                                                                                                                                                                                                    data = request.json
                                                                                                                                                                                                                                                                                                                                                        address = data.get('address')
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                if not address:
                                                                                                                                                                                                                                                                                                                                                                        return jsonify({'success': False, 'error': 'Adresse MAC requise'}), 400
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                        # Tenter la connexion
                                                                                                                                                                                                                                                                                                                                                                                                result = subprocess.run(
                                                                                                                                                                                                                                                                                                                                                                                                            ['bluetoothctl', 'connect', address],
                                                                                                                                                                                                                                                                                                                                                                                                                        capture_output=True,
                                                                                                                                                                                                                                                                                                                                                                                                                                    text=True,
                                                                                                                                                                                                                                                                                                                                                                                                                                                timeout=30
                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if 'Connection successful' in result.stdout:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return jsonify({'success': True})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return jsonify({'success': False, 'error': result.stderr}), 500
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return jsonify({'success': False, 'error': str(e)}), 500

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.run(host='0.0.0.0', port=3000, debug=False)